// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApuholuDFbNS9vYHuJ7-KUXtFAEZqVDMg',
    appId: '1:69259487835:web:4ab8362f3b9057f3466d7e',
    messagingSenderId: '69259487835',
    projectId: 'silent-guardian-64590',
    authDomain: 'silent-guardian-64590.firebaseapp.com',
    storageBucket: 'silent-guardian-64590.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXQOnAahDdEvQ1UZKXMMzMIbXhXoioSmg',
    appId: '1:69259487835:android:9a14b02942372648466d7e',
    messagingSenderId: '69259487835',
    projectId: 'silent-guardian-64590',
    storageBucket: 'silent-guardian-64590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKNDi2RXmBl4Srdg9mD2Ln2S6ezMD2SZk',
    appId: '1:69259487835:ios:97e774379d370c60466d7e',
    messagingSenderId: '69259487835',
    projectId: 'silent-guardian-64590',
    storageBucket: 'silent-guardian-64590.firebasestorage.app',
    iosBundleId: 'com.example.silentGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKNDi2RXmBl4Srdg9mD2Ln2S6ezMD2SZk',
    appId: '1:69259487835:ios:97e774379d370c60466d7e',
    messagingSenderId: '69259487835',
    projectId: 'silent-guardian-64590',
    storageBucket: 'silent-guardian-64590.firebasestorage.app',
    iosBundleId: 'com.example.silentGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApuholuDFbNS9vYHuJ7-KUXtFAEZqVDMg',
    appId: '1:69259487835:web:0b1e1f7f74bbd7ff466d7e',
    messagingSenderId: '69259487835',
    projectId: 'silent-guardian-64590',
    authDomain: 'silent-guardian-64590.firebaseapp.com',
    storageBucket: 'silent-guardian-64590.firebasestorage.app',
  );

}