// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzBMQypSx72bNrQ0oUgEdubvnUE1tSLvU',
    appId: '1:1036717156344:web:2bb08105afde6666d9180d',
    messagingSenderId: '1036717156344',
    projectId: 'silent-guardian-2905d',
    authDomain: 'silent-guardian-2905d.firebaseapp.com',
    storageBucket: 'silent-guardian-2905d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv-h3bLKNzfu4RxfeqVYB9TePyVk9h04M',
    appId: '1:1036717156344:android:7e620cfb1f8c22d0d9180d',
    messagingSenderId: '1036717156344',
    projectId: 'silent-guardian-2905d',
    storageBucket: 'silent-guardian-2905d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_g78zJ4c6NgXFnaHdQJHuUI4fbSXGsqE',
    appId: '1:1036717156344:ios:c47487ae57dc38fcd9180d',
    messagingSenderId: '1036717156344',
    projectId: 'silent-guardian-2905d',
    storageBucket: 'silent-guardian-2905d.firebasestorage.app',
    iosBundleId: 'com.example.silentGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_g78zJ4c6NgXFnaHdQJHuUI4fbSXGsqE',
    appId: '1:1036717156344:ios:c47487ae57dc38fcd9180d',
    messagingSenderId: '1036717156344',
    projectId: 'silent-guardian-2905d',
    storageBucket: 'silent-guardian-2905d.firebasestorage.app',
    iosBundleId: 'com.example.silentGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzBMQypSx72bNrQ0oUgEdubvnUE1tSLvU',
    appId: '1:1036717156344:web:df1e0e1c7799894cd9180d',
    messagingSenderId: '1036717156344',
    projectId: 'silent-guardian-2905d',
    authDomain: 'silent-guardian-2905d.firebaseapp.com',
    storageBucket: 'silent-guardian-2905d.firebasestorage.app',
  );
}
